//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHotel
{
    using System;

    public partial class User
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Code { get; set; }
        public Nullable<long> Phone { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string CardType { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
